Use sys.exit() over exit()
os-autoinst/qa-tools-backlog-assistant pull request #23
Opened 2021-11-25 21:10 UTC by alanyee

Use sys.exit() over exit() as exit() is to be used in the "interactive interpreter shell and should not be used in programs."

Source: https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module

2021-11-25 21:13 UTC, okurz commented
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [git-pr-last](http://github.com/okurz/scripts/tree/master/git-pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2021-11-26 09:45 UTC, perlpunk requested changes
Another comment about the commit message:
* Keep the length of the subject line ideally below 72 characters. Try to break up the most important message and more info about it into a subject and the body
* Always leave a blank line between the actual subject line of the commit and the body.

Various git tools will mess up the formatting if the line is too long or when there is no blank line

2021-11-27 10:17 UTC, okurz approved these changes
Looks good now

2021-11-28 01:48 UTC, perlpunk approved these changes

2021-11-28 12:20 UTC, merged