Use backlogger to provide the backlog status
os-autoinst/qa-tools-backlog-assistant pull request #31
Opened 2022-08-11 19:02 UTC by kalikiana

2022-08-11 19:04 UTC, kalikiana commented
Note: This is **not** required by [poo#113797](https://progress.opensuse.org/issues/113797) but I prepared the query on the side since I wanted to check if the code was still re-usable. Currently the queries won't issue reminders since they don't have `update_on` or `due_date` in them.

2022-12-20 10:52 UTC, kalikiana commented
> Note: This is **not** required by [poo#113797](https://progress.opensuse.org/issues/113797) but I prepared the `queries.yaml` on the side since I wanted to check if the code was still re-usable. Currently the queries won't issue reminders since they don't have `update_on` or `due_date` in them.

In the context of [poo#121582](https://progress.opensuse.org/issues/121582) this is becoming even more useful in tandem with https://github.com/openSUSE/backlogger/pull/15 which allows feeding the same queries into Grafana.

2022-12-21 08:24 UTC, okurz requested changes
Sorry, I don't quite understand the impact of the change. 
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

2023-01-02 10:30 UTC, okurz approved these changes

2023-01-03 13:48 UTC, merged